config/routes.rb
Rails.application.routes.draw do

  get '/login' => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout'  => 'sessions#destroy'

  root 'welcome#index'

  resources :artists
  resources :projects

end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_secure_password
  has_many :projects
end

app/models/project.rb
class Project < ActiveRecord::Base

  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # helpers is a method that takes a symbol of the name of a method
  # it allows us to call the method in a view
  helper_method :current_artist

  # we define current artist here so that we can call it in all the
  # controllers that inherit from ApplicationController
  def current_artist
    # if we stored the artist's id in session
    # then we will search for that artist
    # and assign it to @artist
    @artist = Artist.find_by({id: session[:artist_id]}) if session[:artist_id]
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    artist = Artist.create(artist_params)
    redirect_to artist_path(artist)
  end

  def show
    @artist = Artist.find(params[:id])
  end

  private

  def artist_params
    params.require(:artist).permit(
      :username,
      :biography,
      :artist_statement,
      :password,
      :password_confirmation,
      :picture_url
    )
  end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController



  def new
    # set the project's artist ID to the artist in session
    # then we can hide the artist_id as a hidden field in the form
    @project = Project.new(artist_id: session[:artist_id])
    # @artist  = Artist.find(params[:artist_id])
  end

  def create
    @project = Project.create(project_params)
    # find the artist in session and set it as the project's artist
    # @project.artist_id = session[:artist_id]
    # @project.save
    redirect_to @project.artist
  end

  def destroy
    project = Project.find_by(id: params[:id])
    project.delete
    # current_artist comes from ApplicationController
    redirect_to current_artist
  end

  private

  def project_params
    params.require(:project).permit(
      :name,
      :description,
      :picture_url,
      :artist_id
    )
  end


  # def new
  #   @venue = Venue.find(params[:venue_id])
  #   @event = Event.new
  #   # family-friendly venues should only be presented with family-friendly bands
  #   @bands = @venue.family_friendly ? Band.all : Band.where(explicit_lyrics: false)
  # end

  # def create
  #   @event = Event.create(event_params)
  #   @event.venue_id = params[:venue_id]
  #   @event.save
  #   redirect_to @event
  # end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    artist = Artist.find_by({username: params[:username]})
    # artist = Artist.find_by(username: params[:session][:username].downcase)
    if artist && artist.authenticate(params[:password])
      session[:artist_id] = artist.id
      redirect_to artist_path(artist)
    # if artist && artist.authenticate(params[:session][:password])
      # Log the user in and redirect to the user's show page.
    else
      # Create an error message.
      render 'new'
    end
  end


  def destroy
    session[:artist_id] = nil
    redirect_to root_path
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @artists = Artist.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/artists/index.html.erb
<h1>Artists</h1>

<% @artists.each do |artist| %>
  <li><%= artist.username %>"</li>
<% end %>

app/views/artists/new.html.erb
<h1>Sign Up as a New Artist</h1>

<%= form_for(@artist, class: "form-horizontal") do |f| %>
  <div class="form-group">
  <%= f.label :username %>:
  <%= f.text_field :username %><br />

  <%= f.label :biography %>:
  <%= f.text_area :biography %><br />

  <%= f.label :artist_statement %>:
  <%= f.text_area :artist_statement %><br />

  <%= f.label :password %>:
  <%= f.password_field :password %><br />

  <%= f.label :password_confirmation %>:
  <%= f.password_field :password_confirmation %><br />

  <%= f.label :picture_url  %>:
  <%= f.text_area :picture_url %><br />


  <%= f.submit %>
</div>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.username %></h1>

<h3>Biography</h3>
<p><%= @artist.biography %></p>
<h3>Artist's Statement</h3>
<p><%= @artist.artist_statement %></p>



<p>Show a new Project, finished or In Progress</p>
<%= link_to "Add Project!", new_project_path, class: "btn btn-primary btn-lg" %>

<!-- Artist's Projects -->
<ul>
  <% @artist.projects.each do |project| %>
    <li>
      <h3><%= project.name %></h3>
      <%= button_to "Delete", project, method: :delete %>
      <%= project.description %>
      <%= image_tag project.picture_url %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>In Progress</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "In Progress", root_path, class: "navbar-brand" %>
    </div>

    <div id="navbar" class="navbar-collapse collapse navbar-right">
      <% if current_artist %>
        <%= link_to "Artist Page", artist_path(current_artist), class: "navbar-brand" %>
        <%= button_to "Logout", logout_path, method: :delete %>
      <% else %>
        <%= link_to "Log In as Artist", login_path, class: "navbar-brand" %>
      <% end %>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

<div class="container">
  <div class="row">
    <%= yield %>
  </div>
</div>

</body>
</html>

app/views/projects/new.html.erb
<h1>Your New Project</h1>

<%= form_for(@project, class: "form-horizontal") do |f| %>
  <div class="form-group">
  <%= f.label :name %>:
  <%= f.text_field :name %><br />

  <%= f.label :description %>:
  <%= f.text_area :description %><br />

  <%= f.label :picture_url  %>:
  <%= f.text_area :picture_url %><br />

  <%= f.hidden_field :artist_id %>

  <%= f.submit %>
</div>
<% end %>


<!-- name
description
picture_url -->

app/views/welcome/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to <strong>In Progress</strong></h1>
    <p>This is a website for artists to share their work. Please explore!</p>
    <p>If you are an artist yourself, please
      <%= link_to "Sign Up!", new_artist_path, class: "btn btn-primary btn-lg" %>
    </p>
  </div>

  <div>

  </div>
</div>

<div>

    <!-- <h2>Artists</h2>
    <ul class="list-unstyled">
       <#% @artists.each do |a| %>

       <img src="<#%= a.picture_url %>">
       <li><h3><#%= a.username %></h3></li>
       <#% end %>
    </ul> -->

</div>

<% @artists.each do |artist| %>
  <div class="media">
    <a class="pull-left" href="#">
      <img class="media-object" src="<%= artist.picture_url %>">
    </a>
    <div class="media-body">
      <h4 class="media-heading"><%= artist.username %></h4>
    </div>
  </div>
<% end %>

<!-- <ul class="thumbnails">
  <li class="span4">
    <div class="thumbnail">
      <#% @artists.each do |a| %>
      <img data-src="holder.js/300x200" alt="">
      <h3><#%= a.username %></h3>
      <p>Thumbnail caption...</p>
      <#% end %>
    </div>
  </li>
  ...
</ul> -->